### ISSUE TITLE
@HappyPartyBot 和 @MoeSoaho_bot 都down了

### ISSUE THREAD

**Issue by yangzhaofeng** [sohaking/telegram-happypartybot#1]
然而頻道還有推送，不知是為什麼

**Comment by moesoha** [comment]
后者down了是日常，因为那个bot没啥用了，只是一个lab。
前者啊，推送和消息处理是分开的。因为打算重构，所以我很久没去管它服务是up还是down了。

**Comment by moesoha** [comment]
已重新上线。因为老代码可维护性几乎为0。所以在重构前不会稳定。

关于重构描述在[这里](https://t.me/happypartytrain/315)
